---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dataclone-editor-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
